### ISSUE TITLE
Celo Mondo Epic Wins

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-mondo#66]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-mondo/issues/57
- [ ] https://github.com/celo-org/celo-mondo/issues/54
- [ ] https://github.com/celo-org/celo-mondo/issues/34
- [ ] https://github.com/celo-org/celo-mondo/issues/73
- [ ] https://github.com/celo-org/celo-mondo/issues/74
```
