### ISSUE TITLE
Celo Mondo Epic Bugs

### ISSUE THREAD

**Issue by lvpeschke** [celo-org/celo-mondo#78]
```[tasklist]
### Tasks
- [ ] https://github.com/celo-org/celo-mondo/issues/37
- [ ] https://github.com/celo-org/celo-mondo/issues/32
- [ ] https://github.com/celo-org/celo-mondo/issues/77
```
